services:
  tutorial:
    hostname: fastfusion
    image: fastfusion/fastfusion-infrastructure
    ports:
      - 8888:8888
    volumes:
      - ./:/home/workspace
    stdin_open: true # docker run -i
    tty: true        # docker run -t
