#
# Docker-compose file for running Timeloop-Accelergy-SCE - superconducting electronics arch modeling
#
# Notes: 
#    The READMEs are put in ./workspace
#    The workspace will be owned by $USER_UID:$USER_GID
#

# Run as follows:
#
#    1) Cd to the directory containing this file
#    2) Change USER_UID and USER_GID to the desired owner of your files (echo $UID in Docker Quick Start Terminal)
#    4) Run the following command:
#
#        % If you are using x86 CPU (Intel, AMD)
#        % DOCKER_ARCH=amd64 docker-compose up
#
#        % If you are using arm CPU (Apple M1/M2)
#        % DOCKER_ARCH=arm64 docker-compose up 
#
#        % If you want to avoid typing "DOCKER_ARCH=" every time,
#        % "export DOCKER_ARCH=<your architecture>" >> ~/.bashrc && source ~/.bashrc
#
#    5) Look at output and use the 127.0.0.1 URL (unless you changed the port below)
#

services:
  sce:
    hostname: fastfusion-infrastructure
    image:  fastfusion/fastfusion-infrastructure:latest-${DOCKER_ARCH}
    ports:
      - "8889:8888"
    volumes:
      - ./workspace:/home/workspace
      - ./.dependencies:/.dependencies
    environment:
      - USER_UID=501
      - USER_GID=20
      - JUPYTER_SWITCHES=--NotebookApp.token=''